core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('contact/', views.contact, name='contact'),
    path('', views.IndexLV.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

eCommerce/eCommerce/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

eCommerce/eCommerce/eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # traemos los archivos media


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('items.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import *

app_name = 'items'

urlpatterns = [
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('publicar/', ItemCreateView.as_view(), name="publicar"),
]

core/models.py
from django.db import models

# Create your models here.

eCommerce/eCommerce/core/models.py
from django.db import models

# Create your models here.

core/forms.py
import re
from django import forms
from django.forms import ValidationError


def solo_letras(value):
    if any(char.isdigit() for char in value):
        raise ValidationError('El nombre solo admite letras. %(valor)s',
                            code='Invalid',
                            params={'valor': value})


def custom_validate_email(value):
    email_regex = r'^([\w\-\.]+)@((\[([0-9]{1,3}\.){3}[0-9]{1,3}\])|(([\w\-]+\.)+)([a-zA-Z]{2,4}))$'
    if not re.match(email_regex, value):
        raise ValidationError('Correo electrónico inválido')


class ContactForm(forms.Form):
    nombre = forms.CharField(
        label='Nombre',
        max_length=50,
        validators=(solo_letras,),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Solo letras'
            }
        )
    )
    email = forms.EmailField(
        label='Email',
        max_length=100,
        required=False,
        validators=(custom_validate_email,),
        error_messages={
            'required': 'Por favor completa el campo'
        },
        widget=forms.EmailInput(attrs={'class': 'form-control', 'type': 'email'})
    )
    asunto = forms.CharField(
        label='Asunto',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    mensaje = forms.CharField(
        label='Mensaje',
        max_length=500,
        widget=forms.Textarea(attrs={
            'rows': 5, 
            'class': 'form-control',
            'placeholder': '20 caracteres mínimo',
            }
        )
    )

    def clean_mensaje(self):
        data = self.cleaned_data['mensaje']
        if len(data) < 20:
            raise ValidationError(
                "El mensaje es un acotado, proporciona más detalles.")
        return data

    def clean(self):
        cleaned_data = super().clean()
        asunto = cleaned_data.get("asunto")

core/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from items.models import *
from .forms import *
from django.views.generic import ListView, FormView


# def contact(request):
#     if request.method == "POST":
#         contact_form = ContactoForm(request.POST)
#         mensaje = "Recibimos tu consulta. Gracias por escribirnos."
#         if contact_form.is_valid():
#             messages.success(request, mensaje)
#             contact_form = ContactoForm()
#         else:
#             messages.error(
#                 request, 'Los datos cargados tienen errores, revísalos')
#     elif request.method == "GET":
#         contact_form = ContactoForm()
#     else:
#         HttpResponseNotAllowed(f"Método {request.method} no soportado.")

#     context = {
#         "contact_form": contact_form
#     }

#     return render(request, 'core/contact.html', context)

class IndexLV(ListView):
    model = Item
    template_name = 'core/index.html'

    def get_queryset(self):
        return Item.objects.filter(sold=False).order_by("-created_at")[:5]


class ContactView(FormView):
    form_class = ContactForm
    template_name = 'core/contact.html'
    success_url = reverse_lazy('core:index')
    "¡Consulta enviada correctamente!\nNos comunicaremos a la brevedad"

    def form_valid(self, form):
        messages.success(self.request, "¡Consulta enviada correctamente!\nNos comunicaremos a la brevedad")
        
        return super().form_valid(form)

eCommerce/eCommerce/core/views.py
from django.shortcuts import render
from items.models import *
# Create your views here.

def index(request):
    
    items = Item.objects.filter(is_sold=False) # solo si no estan vendidos
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items' : items,
    })

def contact(request):
    return render(request, 'core/contact.html')

eCommerce/eCommerce/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | eCommerce</title>
</head>
<body>
    <nav class="grid grid-cols-3 gap-4 items-center py-6 px-6 border-b border-gray-500">
        <a href="/" class="col-span-1 justify-self-start text-xl font-semibold shadow-lg">eCommerceCaC</a>
        <div class="col-span-2 flex justify-self-end items-center gap-3">
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Nuevo Item</a>
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}

        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">Acerca de</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        </div>
        <div class="w-1/3">
            <ul class="space-y-2">
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contacto</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Términos de uso</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Política de privacidad</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

eCommerce/eCommerce/core/templates/core/contact.html
{% extends 'core/base.html'%}

{% block title %}Contacto{% endblock %}    

{% block content %}

    <h1>Página de Contato</h1>

{% endblock %}

eCommerce/eCommerce/core/templates/core/index.html
{% extends 'core/base.html'%}

{% block title %}Welcome{% endblock %}    

{% block content %}
    <!-- Contenedor de los productos disponibles -->
    <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Productos nuevos</h2>
        
        <!-- <div class="grid grid-cols-3 gap-3"> -->
        <div class="flex flex-wrap gap-4">
            <!-- Iteramos sobre la base de datos-->
            {% for item in items %}
                <div class="hover:drop-shadow-2xl">
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="flex items-center justify-center bg-white">
                            <!-- Trae las imágenes -->
                            <img src="{{ item.image.url }} " class="h-52">
                        </div>
                        <!-- Trae el nombre y el precio-->
                        <div class="bg-white p-6 rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Precio: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    
    </div>

    <!-- Contenedor de las categorias-->
    <div class="mt-6 px-6 py-12 bg-gray-200 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categorías</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories%}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-t-xl rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} items</p> <!-- Devuelve la cantidad de items por categoria -->
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>    
{% endblock %}