core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('contact/', views.contact, name='contact'),
    path('', views.IndexLV.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

eCommerce/eCommerce/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

eCommerce/eCommerce/eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # traemos los archivos media


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('items.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import *

app_name = 'items'

urlpatterns = [
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('publicar/', ItemCreateView.as_view(), name="publicar"),
]

core/models.py
from django.db import models

# Create your models here.

eCommerce/eCommerce/core/models.py
from django.db import models

# Create your models here.

core/forms.py
import re
from django import forms
from django.forms import ValidationError


def solo_letras(value):
    if any(char.isdigit() for char in value):
        raise ValidationError('El nombre solo admite letras. %(valor)s',
                            code='Invalid',
                            params={'valor': value})


def custom_validate_email(value):
    email_regex = r'^([\w\-\.]+)@((\[([0-9]{1,3}\.){3}[0-9]{1,3}\])|(([\w\-]+\.)+)([a-zA-Z]{2,4}))$'
    if not re.match(email_regex, value):
        raise ValidationError('Correo electrónico inválido')


class ContactForm(forms.Form):
    nombre = forms.CharField(
        label='Nombre',
        max_length=50,
        validators=(solo_letras,),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Solo letras'
            }
        )
    )
    email = forms.EmailField(
        label='Email',
        max_length=100,
        required=False,
        validators=(custom_validate_email,),
        error_messages={
            'required': 'Por favor completa el campo'
        },
        widget=forms.EmailInput(attrs={'class': 'form-control', 'type': 'email'})
    )
    asunto = forms.CharField(
        label='Asunto',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    mensaje = forms.CharField(
        label='Mensaje',
        max_length=500,
        widget=forms.Textarea(attrs={
            'rows': 5, 
            'class': 'form-control',
            'placeholder': '20 caracteres mínimo',
            }
        )
    )

    def clean_mensaje(self):
        data = self.cleaned_data['mensaje']
        if len(data) < 20:
            raise ValidationError(
                "El mensaje es un acotado, proporciona más detalles.")
        return data

    def clean(self):
        cleaned_data = super().clean()
        asunto = cleaned_data.get("asunto")

core/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from items.models import *
from .forms import *
from django.views.generic import ListView, FormView


# def contact(request):
#     if request.method == "POST":
#         contact_form = ContactoForm(request.POST)
#         mensaje = "Recibimos tu consulta. Gracias por escribirnos."
#         if contact_form.is_valid():
#             messages.success(request, mensaje)
#             contact_form = ContactoForm()
#         else:
#             messages.error(
#                 request, 'Los datos cargados tienen errores, revísalos')
#     elif request.method == "GET":
#         contact_form = ContactoForm()
#     else:
#         HttpResponseNotAllowed(f"Método {request.method} no soportado.")

#     context = {
#         "contact_form": contact_form
#     }

#     return render(request, 'core/contact.html', context)

class IndexLV(ListView):
    model = Item
    template_name = 'core/index.html'

    def get_queryset(self):
        return Item.objects.filter(sold=False).order_by("-created_at")[:5]


class ContactView(FormView):
    form_class = ContactForm
    template_name = 'core/contact.html'
    success_url = reverse_lazy('core:index')
    "¡Consulta enviada correctamente!\nNos comunicaremos a la brevedad"

    def form_valid(self, form):
        messages.success(self.request, "¡Consulta enviada correctamente!\nNos comunicaremos a la brevedad")
        
        return super().form_valid(form)

eCommerce/eCommerce/core/views.py
from django.shortcuts import render
from items.models import *
# Create your views here.

def index(request):
    
    items = Item.objects.filter(is_sold=False) # solo si no estan vendidos
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items' : items,
    })

def contact(request):
    return render(request, 'core/contact.html')

templates/core/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | eCommerce</title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <script src="https://kit.fontawesome.com/02bc901fa9.js" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'core/css/card.css'%}">  -->
    {% block css %}{% endblock css %}
</head>

<body>
    <header class="container-fluid border-bottom pt-2" style="background-color: rgb(60, 120, 0);">
        <div class="row px-2 py-1 d-flex align-items-center justify-content-between">
            <div class="col-3">
                <a href="{% url 'core:index' %}" style="text-decoration: none; color: black;">
                    <img src="{% static 'core/img/ecom.png' %}" alt="eCommerce icon" style="width: 50px;">
                    eCommerce
                </a>
            </div>

            <!-- search input form -->
            <div class="col-6">
                <div class="input-group">
                    <input class="form-control border-end-0 border" type="search" placeholder="search"
                        id="example-search-input">
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary bg-white border-start-0 border ms-n5" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>

        <!-- navbar -->
        <div class="row container-fluid align-items-center justify-content-between py-1 px-2">
            <!-- navbar menu -->
            <nav class="col navbar justify-content-evenly">
                <div class="nav-item dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                        aria-expanded="false" style="color: gray;">
                        Categorias
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        {% for category in categories%}
                        <li class="list-unstyled p-1">
                            <a href="#" style="text-decoration: none;">{{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <a href="#" style="text-decoration: none; color: gray;">Historial</a>
                <a href="{% url 'items:publicar' %}" style="text-decoration: none; color: gray;">Vender</a>
                <a href="#" style="text-decoration: none; color: gray;">Ayuda</a>
            </nav>
            <!-- navbar user -->
            <nav class="col navbar justify-content-evenly">
                <a href="#" style="text-decoration: none; color: black;">Registrate</a>
                <!-- Button trigger modal login -->
                <button type="submit" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#login"
                    style="text-decoration: none; color: black;">
                    Ingresá
                </button>
                <!-- Modal -->
                <div class="modal fade" id="login" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Ingreá con tu cuenta</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Form login
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary">Ingresar</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% comment %} user nav {% endcomment %}
                <div class="nav-item p-1">
                    <a href="#" style="text-decoration: none; color: black;">
                        <img src="{% static 'core/img/avatar-profile.png' %}" alt="avatar icon" class="rounded-circle"
                            style="width: 35px;">
                        <span>User</span>
                    </a>
                </div>

                <a href="#" style="text-decoration: none; color: black;">Mis compras</a>

                <div class="nav-item dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                        aria-expanded="false" style="color: black;">
                        Favoritos
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        {% for category in categories%}
                        {% endfor %}
                    </ul>
                </div>

                <a href="#" style="text-decoration: none; color: black;">
                    <i class="fa-solid fa-cart-shopping" style="color: #000000;"></i>
                </a>
            </nav>
        </div>
    </header>


    {% block content %}{% endblock %}


    {% include "core/footer.html" %}
</body>

</html>

templates/core/base_2.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | eCommerce</title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <script src="https://kit.fontawesome.com/02bc901fa9.js" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'core/css/card.css'%}">  -->
    {% block css %}{% endblock css %}
</head>
<body>
    <header class="container-fluid border-bottom bg-light">
        <div class="row px-2 py-1 d-flex align-items-center justify-content-between">
            <div class="col-3">
                <a href="{% url 'core:index' %}" style="text-decoration: none; color: black;">
                    <img src="{% static 'core/img/ecom.png' %}" alt="eCommerce icon" style="width: 50px;">
                    eCommerce
                </a>
            </div>

            <nav class="col-5 navbar justify-content-evenly">
                <a href="#" style="text-decoration: none; color: black;">Registrate</a>
                <!-- Button trigger modal login -->
                <button type="submit" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#login" style="text-decoration: none; color: black;">
                    Ingresá
                </button>
                <!-- Modal -->
                <div class="modal fade" id="login" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ingreá con tu cuenta</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Form login
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Ingresar</button>
                        </div>
                    </div>
                    </div>
                </div>
                {% comment %}                  
                    <div class="nav-item p-1">
                        <a href="#" style="text-decoration: none;">
                            <img src="{% static "core/img/avatar-profile.png" %}" alt="avatar icon" class="rounded-circle" style="width: 35px;">
                            <span>Usuario Pepe</span>
                        </a>
                    </div>
                {% endcomment %}
                <a href="#" style="text-decoration: none; color: black;">Mis compras</a>
                {% comment %}
                <div class="nav-item dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="color: black;">
                        Favoritos
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    {% for category in categories%}
                    {% endfor %}
                    </ul>
                </div> -->
                {% endcomment %}
                <a href="#" style="text-decoration: none; color: black;">
                    <i class="fa-solid fa-cart-shopping" style="color: #000000;"></i>
                </a>
            </nav>
        </div>

    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    {% include "core/footer.html" %}
</body>
</html>

templates/core/contact.html
{% extends 'core/base_2.html'%}

{% block title %}Contacto{% endblock %}    

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-4 my-2 border rounded shadow-sm">
                <form id="contact-form" name="contact-form" action="" method="POST">
                    {% csrf_token %} {{ form.as_p }}
                    <div class="text-center m-2">
                        <button type="reset" class="btn btn-danger mx-2">Borrar datos</button>
                        <button type="submit" class="btn btn-primary mx-2">Enviar</button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/core/footer.html
<footer class="container-fluid row border-top my-2">
    <div class="col p-2">
        <h3>Nosotros</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    </div>
    <div class="col p-2">
        <ul>
            <li class="list-unstyled">
                <a href="{% url 'core:contact' %}" style="text-decoration: none;">Contacto</a>
            </li>
            <li class="list-unstyled">
                <a href="#" style="text-decoration: none;">Términos de uso</a>
            </li>
            <li class="list-unstyled">
                <a href="#" style="text-decoration: none;">Política de privacidad</a>
            </li>
        </ul>
    </div>
</footer>

templates/core/index.html
{% extends 'core/base.html'%}

{% block title %}Bienvenidos{% endblock %}

{% block content %}
    <!-- Contenedor de los productos disponibles -->
    <div class="container-fluid justify-content-centerp-2 bg-secondary">
        <div class="row container justify-content-center p-2">
        {% if object_list %}
            {% for item in object_list %}
                <div class="card col mx-4 shadow rounded" style="max-width: 300px;">
                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        <img src="{{ item.images.url }}" class="img-fluid" style="width: 200px;"/>
                        <a href="{% url 'items:detail' item.id %}" class="card-link stretched-link"></a>
                    </div>
                    {% comment %}<div class="card-header" style="font-size: smaller;">{{ item.created_at|date:"d-m-Y" }}</div>{% endcomment %}
                    <div class="card-header" style="font-size: smaller;">{{ item.category }}</div>
                    <div class="card-body">
                        <h4 class="card-text"><span>${{ item.price }}</span></h4>
                        <div class="card-title text-truncate">{{ item.title }}</div>
                    </div>
                    <p class="card-footer">Publicado por: <b>{{item.created_by}}</b></p>
                </div>
            {% endfor %}
        {% else %}
            <h4>No hay artículos publicados.</h4>
        {% endif %}
        
        </div>
    </div>
{% endblock %}